from Funciones_Login import *
def menu_login_adm():
    print("-"*50)
    print(" " * ((50 - len("Menú Login Administradors")) // 2) + "Menú Login Administradors")
    print("-"*50)
    print("\n")
    print("1. Iniciar Sesión")
    #print("2. Registrarse")
    print("2. Salir")
def menu_login():
    print("-"*50)
    print(" " * ((50 - len("Menú Login")) // 2) + "Menú Login")
    print("-"*50)
    print("\n")
    print("1. Iniciar Sesión")
    #print("2. Registrarse")
    print("2. Salir")
def menu_gestio_hospital_adm():
    print("-"*50)
    print(" " * ((50 - len("Menu gestió hospital Administradors")) // 2) + "Menu gestió hospital Administradors")
    print("-"*50)
    print("\n")
    print("1. Manteniments")
    print("2. Salir")
def menu_gestio_hospital():
    print("-"*50)
    print(" " * ((50 - len("Menu gestió hospital")) // 2) + "Menu gestió hospital")
    print("-"*50)
    print("\n")
    print("1. Manteniments")
    print("2. Consultes i informes")
    print("3. Exportació de dades")
    print("4. Dummy Data")
    print("5. Salir")
def menu_manteniments_adm():
    print("-"*50)
    print(" " * ((50 - len("Menú de manteniments Administradors")) // 2) + "Menú de manteniments Administradors")
    print("-"*50)
    print("\n")
    print("1. Donar d'alta a nou personal del centre")
    print("2. Donar d'alta a nou pacient")
    print("3. Sortir")
def menu_manteniments():
    print("-"*50)
    print(" " * ((50 - len("Menú de manteniments")) // 2) + "Menú de manteniments")
    print("-"*50)
    print("\n")
    print("1. Informació de les infermeres")
    print("2. Operacions previstes per dia")
    print("3. Visites planificades per dia")
    print("4. Obtener reservas por habitacion")
    print("5. Obtener informacion de un paciente")
    print("6. Obtener equipos por quirofano")
    print("7. Obtener informacion de un medico")
    print("8. Sortir")
def menu_consultes_informes():
    print("-"*50)
    print(" " * ((50 - len("Menu de consultes i informes")) // 2) + "Menu de consultes i informes")
    print("-"*50)
    print("\n")
    print("1. Consulta de les plantes")
    print("2. Informe de personal")
    print("3. Informe de nombre de visites ateses per dia")
    print("4. Informe de Clasificación de Médicos con Mayor Número de Pacientes Atendidos")
    print("5. Informe de las Enfermedades Más Comunes")
    print("6. Sortir")
def menu_dummy_data():
    print("-"*50)
    print(" " * ((50 - len("Menu Dummy Data")) // 2) + "Menu del Dummy Data")
    print("-"*50)
    print("\n")
    print("1. Inserció de dades")
    print("2. Eliminació total de les dades")
    print("3. Sortir")   